version: "3"

services:
  app:
    build:
      context: .
    environment:
      PORT: 5433
    ports:
      - 5433:5432
    volumes:
      - ./conf/docker.yaml:/conf.yaml
    depends_on:
      - pg1_1
      - pg1_2
      - pg2_1
      - pg2_2

  pg1_1:
    image: postgres:13
    environment: &pg_env
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 54321:5432
    volumes:
      - pg1-1:/var/lib/postgresql/data
      - ./conf/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
      - ./conf/postgres.conf:/etc/postgresql/postgresql.conf
      - ./conf/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf

  pg1_2:
    image: postgres:13
    environment:
      <<: *pg_env
      MASTER: pg1_1
    depends_on:
      - pg1_1
    ports:
      - 54322:5432
    volumes:
      - pg1-2:/var/lib/postgresql/data
      - ./conf/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
      - ./conf/postgres.conf:/etc/postgresql/postgresql.conf
      - ./conf/pg_hba.conf:/etc/postgresql/pg_hba.conf

  pg2_1:
    image: postgres:13
    environment:
      <<: *pg_env
    ports:
      - 54323:5432
    volumes:
      - pg2-1:/var/lib/postgresql/data
      - ./conf/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
      - ./conf/postgres.conf:/etc/postgresql/postgresql.conf
      - ./conf/pg_hba.conf:/etc/postgresql/pg_hba.conf

  pg2_2:
    image: postgres:13
    environment:
      <<: *pg_env
      MASTER: pg2_1
    depends_on:
      - pg2_1
    ports:
      - 54324:5432
    volumes:
      - pg2-2:/var/lib/postgresql/data
      - ./conf/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
      - ./conf/postgres.conf:/etc/postgresql/postgresql.conf
      - ./conf/pg_hba.conf:/etc/postgresql/pg_hba.conf

volumes:
  pg1-1:
    driver: local
  pg1-2:
    driver: local
  pg2-1:
    driver: local
  pg2-2:
    driver: local
